### ISSUE TITLE
Accessories

### ISSUE THREAD

**Issue by pelomedusa** [klesh/ergodone-3d-printing-case#1]
Hi,
Do you have links to buy the accessories? Unfortunately in don't read the language it's written in.
Thanks

**Comment by klesh** [comment]
Oh, I do. But it is Chinese website as those screen-shot showed, which was taobao.com
I dont think links would help you because you also need to choose the specs on page, and shipping might be expensive.
I think you could opt for buying some similar looking items with exactly same specs.

**Comment by pelomedusa** [comment]
Hello @klesh,
Sorry for bothering you again, I'm having a little bit of trouble building this (first time);

- First of all, have this been build/tested before? (Probably should have asked this before printing :) )
- I can guess the "m3x8 沉头螺丝" are for keeping the bottom and top parts together on each corners, however i'm not sure what to do with the stands off  and the "m5x6x6". Am i supposed to screw the PCB to the bottom part with them? Because the holes do not seems to be aligned.

If i manage to build this, and with your authorization, i would love to post this on Thingiverse. 
Thanks a lot

**Comment by klesh** [comment]
Yes, I did. Check the following link for the final product:
https://imgur.com/fXFOZeh

place the screw inserts 
![image](https://user-images.githubusercontent.com/61080/77138509-3d62e800-6aad-11ea-88dc-aadaeaf5f2bd.png)
to following places
![image](https://user-images.githubusercontent.com/61080/77138446-0e4c7680-6aad-11ea-8fe5-0ef7b9b31a33.png)
then, close the case with m3x8 screws.
after that, you will have 3 screw holes on sides of the case.
so that you can attach m5x50 quickrelease screws to the case as stands.

feel free to post them to anywhere as long as it has a link to this github repository.

**Comment by pelomedusa** [comment]
Looks great! Thank you so much for this. So the standoffs (m3x9 双通铜柱 20pcs) are not needed?

I will of course give you credit and link the repository.

**Comment by klesh** [comment]
You are right, they are optional. Glad that I can help.
